module HOMMCONSTS
    # Hero Moving
    HERO_MOVE_RECOVERY = 20
    HERO_MAX_MOVE = 30
    HERO_MOVE_COST = 4

    # Resource Incomes (1/100 of homm for reference)
    CITY_BITCOIN_INCOME_LEVEL1 = 5
    CITY_BITCOIN_INCOME_LEVEL2 = 10
    CITY_BITCOIN_INCOME_LEVEL3 = 20
    BITCOIN_GROUNDITEM_INCOME = 10
    BITCOIN_FARM_INCOME = 5
    POT_GROUNDITEM_VALUE = 3
    POT_FARM_INCOME = 1
    CEREAL_GROUNDITEM_VALUE = 3
    CEREAL_FARM_INCOME = 1

    # Building Costs (rangers)
    TIER2_BUILDING_COST_BITCOIN = 15
    TIER2_BUILDING_COST_POT = 0
    TIER2_BUILDING_COST_CEREAL = 0

    # Building Costs (cavalry)
    TIER3_BUILDING_COST_BITCOIN = 20
    TIER3_BUILDING_COST_POT = 0
    TIER3_BUILDING_COST_CEREAL = 3

    # Building Costs (ballista)
    TIER4_BUILDING_COST_BITCOIN = 25
    TIER4_BUILDING_COST_POT = 3
    TIER4_BUILDING_COST_CEREAL = 7

    # Building Costs (wizard)
    TIER5_BUILDING_COST_BITCOIN = 35
    TIER5_BUILDING_COST_POT = 5
    TIER5_BUILDING_COST_CEREAL = 10

    # Unit Data
    TIER1_COST = 1
    TIER1_DAMAGE = 2
    TIER1_HEALTH = 2
    TIER1_SPAWNRATE = 10
end