module HOMMCONSTS
    # Hero Moving
    HERO_MOVE_BASE = 3
    HERO_MAX_MOVE = 7
    HERO_MOVE_COST = 1

    # Resource Incomes 
    CITY_BITCOIN_INCOME_LEVEL1 = 3
    CITY_BITCOIN_INCOME_LEVEL2 = 6
    CITY_BITCOIN_INCOME_LEVEL3 = 9

    BITCOIN_GROUNDITEM_INCOME = 10
    BITCOIN_FARM_INCOME = 3

    POT_GROUNDITEM_VALUE = 3
    POT_FARM_INCOME = 1

    CEREAL_GROUNDITEM_VALUE = 3
    CEREAL_FARM_INCOME = 1

    # Cost to upgrade bitcoin/defense/meme
    LEVEL2_BITCOIN_UPGRADE_COST = 25
    LEVEL3_BITCOIN_UPGRADE_COST = 50

    LEVEL1_DEFENSE_COST_BITCOIN = 10
    LEVEL1_DEFENSE_COST_CEREAL = 0

    LEVEL2_DEFENSE_COST_BITCOIN = 20
    LEVEL2_DEFENSE_COST_CEREAL = 5

    LEVEL3_DEFENSE_COST_BITCOIN = 40
    LEVEL3_DEFENSE_COST_CEREAL = 15


    LEVEL1_MEME_COST_BITCOIN = 15
    LEVEL1_MEME_COST_POT = 5

    LEVEL2_MEME_COST_BITCOIN = 30
    LEVEL2_MEME_COST_POT = 7

    LEVEL3_MEME_COST_BITCOIN = 60
    LEVEL3_MEME_COST_POT = 9


    # Building Costs (rangers)
    TIER2_BUILDING_COST_BITCOIN = 15
    TIER2_BUILDING_COST_POT = 0
    TIER2_BUILDING_COST_CEREAL = 0

    # Building Costs (cavalry)
    TIER3_BUILDING_COST_BITCOIN = 20
    TIER3_BUILDING_COST_POT = 0
    TIER3_BUILDING_COST_CEREAL = 3

    # Building Costs (ballista)
    TIER4_BUILDING_COST_BITCOIN = 25
    TIER4_BUILDING_COST_POT = 3
    TIER4_BUILDING_COST_CEREAL = 7

    # Building Costs (wizard)
    TIER5_BUILDING_COST_BITCOIN = 35
    TIER5_BUILDING_COST_POT = 5
    TIER5_BUILDING_COST_CEREAL = 9

    # Unit Data
    TIER1_COST = 1
    TIER1_DAMAGE = 2
    TIER1_DAMAGE_RAND = 1
    TIER1_HEALTH = 3*3
    TIER1_SPAWNRATE = 8

    TIER2_COST = 2
    TIER2_DAMAGE = 1
    TIER2_DAMAGE_RAND = 0
    TIER2_HEALTH = 1*3
    TIER2_SPAWNRATE = 5

    TIER3_COST = 3
    TIER3_DAMAGE = 3
    TIER3_DAMAGE_RAND = 3
    TIER3_HEALTH = 5*3
    TIER3_SPAWNRATE = 3

    TIER4_COST = 5
    TIER4_DAMAGE = 1
    TIER4_DAMAGE_RAND = 6
    TIER4_HEALTH = 8*3
    TIER4_SPAWNRATE = 2

    TIER5_COST = 8
    TIER5_DAMAGE = 6
    TIER5_DAMAGE_RAND = 2
    TIER5_HEALTH = 5*3
    TIER5_SPAWNRATE = 5

    HERO_COST = 10

    # Battle Things
    BATTLE_ARENA_HEIGHT = 10
    BATTLE_ARENA_WIDTH = 25
    BATTLE_ARENA_SPAWNZONE = 10


end